### PR TITLE
fix: Resolve value of env variables before invoking cross-spawn

### LINKED ISSUE #90: Resolving vars in other vars
On `master`, `cross-env MY_VAR=$MY_OTHER_VAR echo $MY_VAR` on Windows results in this command: `%MY_OTHER_VAR% echo %MY_VAR%`, which is incorrect. #86 fixes this.

On `next` (i.e. with #86 merged), it results in `echo %MY_VAR%`, which is correct. However, in the spawned process, `process.env.MY_VAR` is `%MY_OTHER_VAR%`, which is not very useful, and I would expect it to be *the value* of `MY_OTHER_VAR` from the environment in which cross-env is run.

An easy solution would be to replace variables by their value instead of their platform-specific form (cross-var does this), but I'm not sure that's what we want. In this scenario, `cross-env MY_VAR=$MY_OTHER_VAR echo $MY_VAR` becomes `echo <value of MY_OTHER_VAR>`.

Another solution is replace variables by their value *only* in the part of the command that sets new variables. In this scenario, `cross-env MY_VAR=$MY_OTHER_VAR echo $MY_VAR` becomes `echo %MY_VAR%` like today but `MY_VAR` is properly set to `<value of MY_OTHER_VAR>`. I think this is better, but it requires more work as `commandConvert` needs to be split into two or cover the two cases.

What do you think?

### PR DESCRIPTION
**Pull request by DanReyLop**
Since this was the only blocker for releasing the next major version, I decided to give it a try.

Before:
`cross-env FOO=$NODE_ENV echo $FOO`
Output (before this PR): `"$NODE_ENV"` on UNIX, `"%NODE_ENV%"` on Windows.
Output (after this PR): `"development"` (or whatever value NODE_ENV has)

I've added some logic in the part of the parser that processes the right-hand side of variable assignments (in this example, the `$NODE_ENV` in the `FOO=$NODE_ENV` expression). It will find all occurences of UNIX-style env variables and replace them with their value.

I've also had to change the program logic a little bit so `commandConvert` only operates on the real command and its arguments, not on the variable assignments.

Fixes #90

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -26,9 +26,9 @@ function crossEnv(args) {
 
 function getCommandArgsAndEnvVars(args) {
   const envVars = getEnvVars()
-  const commandArgs = args.map(commandConvert)
-  const command = getCommand(commandArgs, envVars)
-  return [command, commandArgs, envVars]
+  const commandArgs = args.slice()
+  const command = commandConvert(getCommand(commandArgs, envVars))
+  return [commandConvert(command), commandArgs.map(commandConvert), envVars]
```
Comment (hgwood) [inline src/index.js]: - `map` does not mutate its argument so no need to `slice` first
- So the command is converted twice? Is that on purpose?

Comment (DanReyLop) [inline src/index.js]: > So the command is converted twice? Is that on purpose?

No, that was a mistake. Fixed. Good catch!

> map does not mutate its argument so no need to slice first

`getCommand` mutates its first argument (`commandArgs`), so the `.slice` is necessary.

Comment (hgwood) [inline src/index.js]: Oh, I see. You are leveraging the fact that `getCommand` will strip env setters and the command from `commandArgs`. And you are making a copy so that `getCommandArgsAndEnvVars` does not itself mutate its argument. Am I correct? I think this is not very clear from the code. I understand it is done like this to minimize impact on existing code. It might still be a good idea to rename `getCommand` to something more revealing. However, the more I think about a name for this, the more I realize it does too much to have a good name:
- it strips env setters and the command from its first argument
- it sets env vars on its second argument
- it returns the command

A possible improvement would be to replace it with 2 functions:
- args -> [env setters, command, commandArgs] (simple to use using destructuring)
- env setters -> map of env vars (to be merged with `process.env` to form the env for the new process)

What do you think? Is it worth the work?

Comment (DanReyLop) [inline src/index.js]: > You are leveraging the fact that getCommand will strip env setters and the command from commandArgs. And you are making a copy so that getCommandArgsAndEnvVars does not itself mutate its argument. Am I correct?

Correct. If I didn't make a copy, a call to `crossEnv` would get its arguments mutated, and I don't think we want that :)

> A possible improvement would be to replace it with 2 functions...

That sound good, this part was the most confusing when I started looking at this repo, so I think it's totally worth it to refactor a bit.

Comment (kentcdodds) [inline src/index.js]: In addition, we could probably refactor out the whole loop to simplify the code a bit and remove the mutation. 😀

**Comment by DanReyLop** [comment]
What do you folks think about it now? https://github.com/kentcdodds/cross-env/pull/95/commits/53776d3949210ca32bcdb9ab744db38bd7644884

I believe it's a bit cleaner now but I've written it 5 minutes ago so I may be a bit biased :)

**Comment by kentcdodds** [comment]
Hey @danielo515, thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the CONTRIBUTING.md file (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by danielo515** [comment]
Dear @kentcdodds 

Thank you very much. I'm not sure why are no notifying me on this pull request (convenience I guess), but I'm glad to become a collaborator.

Regards

**Comment by DanReyLop** [comment]
@danielo515 I think he mispelled my name haha

**Comment by kentcdodds** [comment]
😅 whoops! Yeah, sorry about that @danielo515, I appreciate your contributions as well! I have a fairly open contributors policy so if anything comes up, feel free to jump in with a PR. I generally give contrib rights to anyone who's contributed non-trivial code changes :)
